### ISSUE TITLE
How to resolve this Exception: Could not find Configuration class [io.eventuate.tram.sagas.spring.participant.SagaParticipantConfiguration]

### ISSUE THREAD

**Issue by konradahodan** [microservices-patterns/ftgo-application#142]
`io.eventuate.tram.sagas.spring.participant.SagaParticipantConfiguration` from    this dependencies : `compileOnly "io.eventuate.tram.sagas:eventuate-tram-sagas-spring-participant:0.14.0.RELEASE"`

Same error for `io.eventuate.tram.spring.events.publisher.TramEventsPublisherConfiguration`

Thanks for your help !

**Comment by cer** [comment]
Please provide more context:

* Version of the code, i.e. git commit
* What are you running that results in this exception. Stack trace?

**Comment by konradahodan** [comment]
- I'm was on the `development` branch 
- Error on build phase . 

I resolve that for update, all dependencies.

Thanks so much.
