### ISSUE TITLE
Issue building MySQL 

### ISSUE THREAD

**Issue by s-stefanov** [microservices-patterns/ftgo-application#160]
There are problems with building MySQL containers right now. 

Missing files in the Dockerfile from the common repository, more specific to 
`ADD https://raw.githubusercontent.com/eventuate-tram/eventuate-tram-sagas/master/mysql/tram-saga-schema.sql /docker-entrypoint-initdb.d/template3`

I'm unsure which version I should revert to follow the book and also have support for arm64 images.
I will be grateful if you can support me here. Saw you made changes from other PRs and Issues for the new image types.

**Comment by cer** [comment]
Sorry about this problem.
The  solution is to change those URLs for the sql scripts: instead of master use the version specified in Gradle.properties.
Try hardwiring the version - it would be better to use Dockerfile ARG

**Comment by s-stefanov** [comment]
Yes, working correctly now.
Initially, this was my idea also to not use master but didn't notice the tram SQL was in a different repository, sorry.

Closing the issue, thank you for the quick response!
