### ISSUE TITLE
compileJava failure in ftgo-delivery-service using Java 19.0.1

### ISSUE THREAD

**Issue by GregoryWalters** [microservices-patterns/ftgo-application#169]
**If I need to use a different Java version, that is not a problem. Just let me know which is best.**

I down graded to Java 1.8 and got it to work. This can be closed.

ftgo-application>gradlew buildContracts assemble

> Task :buildSrc:compileGroovy
Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

> Task :ftgo-common:compileJava
Note: C:\ftgo-application\ftgo-common\src\main\java\net\chrisrichardson\ftgo\common\MoneyModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :ftgo-api-gateway:compileJava
Note: C:\\ftgo-application\ftgo-api-gateway\src\main\java\net\chrisrichardson\ftgo\apiagateway\orders\OrderHandlers.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :ftgo-delivery-service:ftgoJSONSchemaToPojoCodeGenFtgoRestaurantService FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ftgo-delivery-service:ftgoJSONSchemaToPojoCodeGenFtgoRestaurantService'.
> URL contains an invalid URI syntax: file:/C:/ftgo-application/ftgo-delivery-service/build/ftgo-api-specs/ftgo-restaurant-service-api-spec/messages/

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 42s
38 actionable tasks: 38 executed

C:\ftgo-application>java -version
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

**Comment by cer** [comment]
"I down graded to Java 1.8 and got it to work. This can be closed."
