### ISSUE TITLE
"eventuate.message" table how to auto create?

### ISSUE THREAD

**Issue by wukongshuo** [microservices-patterns/ftgo-application#180]
When I try to create a simple customer service and create a post request customer interface, I encounter an error, but I don't know which configuration determines this.  Which configuration enables the automatic creation of the corresponding table?   ”org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [insert into eventuate.message(id, destination, headers, payload, creation_time, published) values(?, ?, ?, ?, ROUND(UNIX_TIMESTAMP(CURTIME(4)) * 1000), ?)]; nested exception is java.sql.SQLSyntaxErrorException: Table 'eventuate.message' doesn't exist“

**Comment by cer** [comment]
You have two options:

* Use a MySQL/Postgres container image that has the predefined schema - that's what the FTGO application is doing
* Use Flyway to create the schema on demand: See https://github.com/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders/blob/2c1f8dd69b32710b7a453d9f4991b4b67a0e5ac9/customer-service/customer-service-messaging/build.gradle#L39
