### ISSUE TITLE
ftgo-api-gateway-graphql is not started - npm run build fails

### ISSUE THREAD

**Issue by asn25** [microservices-patterns/ftgo-application#40]
Hello,

I saw similar issue regarding to NPM in 'Closed Issues', but it seems it's not fixed. Probably some issue with "apollo-link" or  "graphql" node modules..? I run "docker-compose up" and process is stopped on ftgo-api-gateway-graphql image. Log is below:

Building ftgo-api-gateway-graphql
Step 1/8 : FROM node:9.11.2-alpine
 ---> a56170f59699
Step 2/8 : COPY package.json .
 ---> Using cache
 ---> eec02734a7f0
Step 3/8 : RUN npm install
 ---> Using cache
 ---> aea01fab0a59
Step 4/8 : RUN npm install -g typescript
 ---> Using cache
 ---> affb08b85f6f
Step 5/8 : COPY tsconfig.json .
 ---> Using cache
 ---> ee7f97b51435
Step 6/8 : ADD src ./src
 ---> bed2fa2a8f4d
Step 7/8 : RUN npm run build
 ---> Running in 42b887170e7c

> @ build /
> tsc

node_modules/apollo-link/lib/types.d.ts(2,30): error TS7016: Could not find a declaration file for module 'graphql/language/ast'. '/node_modules/graphql/lang
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql/language/ast';`
node_modules/apollo-link/lib/types.d.ts(3,33): error TS7016: Could not find a declaration file for module 'graphql/execution/execute'. '/node_modules/graphql
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql/execution/execute';`
node_modules/apollo-utilities/lib/directives.d.ts(1,85): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.j
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/apollo-utilities/lib/fragments.d.ts(1,30): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/apollo-utilities/lib/getFromAST.d.ts(1,79): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.j
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/apollo-utilities/lib/storeUtils.d.ts(1,192): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/apollo-utilities/lib/transform.d.ts(1,127): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.j
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/apollo-utilities/lib/util/errorHandling.d.ts(1,33): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/Interfaces.d.ts(1,190): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/mock.d.ts(1,86): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/index.js' impli
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/schemaGenerator.d.ts(1,103): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graphql/ind
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/stitching/delegateToSchema.d.ts(1,163): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/stitching/introspectSchema.d.ts(1,31): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/g
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.d.ts(2,68): error TS7016: Could not find a declaration file for module 'graphql'. '/node
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
node_modules/graphql-tools/dist/stitching/mergeSchemas.d.ts(1,49): error TS7016: Could not find a declaration file for module 'graphql'. '/node_modules/graph
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql';`
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-02T00_31_36_609Z-debug.log
ERROR: Service 'ftgo-api-gateway-graphql' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 2

==============
PS. Here is Dockerfile:

FROM node:9.11.2-alpine
COPY package.json .
RUN npm install
RUN npm install -g typescript
COPY tsconfig.json .
ADD src ./src
RUN npm run build
CMD npm run start

If I comment line with "RUN npm run build", then process is going further, all images are created and started. But I guess there will be no UI...

Will be grateful for advice.
Andrew

**Comment by cer** [comment]
Sorry about this. I'm working on a fix. NodeJS dependencies aren't completely stable, e.g. reminds me of quicksand.

Fortunately, the `ftgo-api-gateway-graphql` is optional.
I'd simply comment out the container in docker-compose.yml

**Comment by cer** [comment]
temporary workaround: https://github.com/microservices-patterns/ftgo-application/commit/2cfd2afb998244be0c22b9448e59d9e22259c279
