### ISSUE TITLE
How Order History Service works without AWS account and how to see DB changes?

### ISSUE THREAD

**Issue by asn25** [microservices-patterns/ftgo-application#54]
Hello, 

I'm exploring EntToEndTests. It passes OK. It has a part "verifyOrderHistoryUpdated(int orderId, int consumerId)" - it seems it passes OK as well.
Questions:

1) How  it works without AWS account? DynamoDB is AWS service. As of my experience with AWS, you need to create account to use AWS services...

2) How could one check updates in DynamoDB? F.e. I can see updates in MySQL schemas of main services in IntelliJ IDEA using MySQL Datasource in "Database"-tab. How should one configure DynamoDB connection, what should be connection properties (user, password, schema?) and what tool is appropriate to see DB changes?

Thanks,
Andrew

**Comment by cer** [comment]
The application uses https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html

There are two containers:

* [dynamodblocal](https://github.com/microservices-patterns/ftgo-application/blob/master/docker-compose.yml#L206) - DynamoDB Local
* [dynamodblocal-init](https://github.com/microservices-patterns/ftgo-application/blob/e6a7771f6201bfaa6e3fa872d98c57ae0c79358f/docker-compose.yml#L213) - creates the DynamoDB schema

You can access DynamoDB tables using the [AWS CLI](https://aws.amazon.com/cli/):

```
export AWS_ACCESS_KEY_ID=id_key AWS_SECRET_ACCESS_KEY=access_key
aws --region ignored --endpoint-url http://$DOCKER_HOST_IP:8000 dynamodb scan --table-name ftgo-order-history
```
