### ISSUE TITLE
EndToEndTest should produce three items in OrderHistoryService, but produces one

### ISSUE THREAD

**Issue by asn25** [microservices-patterns/ftgo-application#62]
Hi, 

I run EndToEndTest that makes 3 separate actions on order: create, revise, cancel.
I expect that in Order History data there will be 3 items (positions) corresponding to these actions and reflecting the history of order changes.
But in OrderHistory data there is only one item (position) with the latest order status (CANCELLED):

----------------

{
    "Items": [
        {
            "lineItems": {
                "L": [
                    {
                        "M": {
                            "quantity": {
                                "N": "5"
                            },
                            "price": {
                                "S": "12.34"
                            },
                            "menuItemId": {
                                "S": "1"
                            },
                            "menuItemName": {
                                "S": "Chicken Vindaloo"
                            }
                        }
                    }
                ]
            },
            "keywords": {
                "SS": [
                    "Chicken",
                    "My",
                    "Restaurant",
                    "Vindaloo"
                ]
            },
            "orderId": {
                "S": "5"
            },
            "restaurantName": {
                "S": "My Restaurant"
            },
            "consumerId": {
                "S": "5"
            },
            "orderStatus": {
                "S": "CANCELLED"
            },
            "creationDate": {
                "N": "1577192364222"
            },
            "restaurantId": {
                "N": "5"
            },
            "events.net.chrisrichardson.ftgo.orderservice.domain.Order5": {
                "S": "0000016f37fda115-0242ac12000a0000"
            }
        }
    ],
    "Count": 1,
    "ScannedCount": 1,
    "ConsumedCapacity": null
}

**Comment by cer** [comment]
An item is an Order.
So one order = one item.

**Comment by asn25** [comment]
But where it this item is a "history"? It contains only the latest state. So what is the difference between OrderService-data and OrderHistory-data?

Where is, f.e., an entry with APPROVED status, that should be added after createOrder-operation?

**Comment by cer** [comment]
Oh ic the source of the confusion. 
It's not the history of individual orders. 
It's the history of a Customer, i.e. the orders that they have placed.
