### ISSUE TITLE
DOCKER_HOST_IP is not set or is blank

### ISSUE THREAD

**Issue by LlorandoLau** [microservices-patterns/ftgo-application#84]
Hi,

I have run set-env.sh to set DOCKER_HOST_IP and it echos my ip:

but when I run the command to check whether the var is set, it shows:
**DOCKER_HOST_IP is not set or is blank**
![TIM截图20200407143640](https://user-images.githubusercontent.com/28216165/78637593-3fb2a800-78dd-11ea-9d68-458acecf25a2.png)

Thanks for your help

**Comment by cer** [comment]
`set-env.sh` needs to set environment variables within the current shell, not a nested shell.
Run `source set-env.sh` or `. set-env.sh`.
