### ISSUE TITLE
Many compilation errors after importing into STS? Am I missing something?

### ISSUE THREAD

**Issue by prakashid2** [microservices-patterns/ftgo-application#86]
Hi.

Steps I followed
1. File -> Import -> Projects from Git(with smart import)
2. Given URI. Host. Repository Path. etc.
3. Clone sub projects
4. Finish
5. Configure -> Add Gradle Nature
The 5th step took some time say 5 mins
6. Did a clean build for all projects in the Workspace. Build Automatically was selected.

After this I'm seeing around 24 errors (see screnshot) in Workspace. Just opened one error from the OrderServiceServer.java. It's saying OrderServiceGrpc cannot be resolved to a type(see screenshot). How to get rid of this error in STS?
The README file says something about building Contracts. Is this error related to same? On Command line I'm able to run gradlew buildContract without any errors. Is there a way in STS also to get rid of this error? How you used to do it in the dev?

Thanks
Prakash S.
Mumbai, India

**Comment by prakashid2** [comment]
![CompilationErrorsAfterImportingFromGithub](https://user-images.githubusercontent.com/35317036/79639396-33fe9580-81a9-11ea-9a78-1d53ca47fb07.jpg)

![ImportingFromGitRepository-2](https://user-images.githubusercontent.com/35317036/79639415-4678cf00-81a9-11ea-81dd-659bd165e969.jpg)

**Comment by cer** [comment]
Quick answer: 

1. `git clone` to the filesystem
2. Run `./gradlew buildContracts assemble`
3. `File->Import->Existing Gradle Project` into Eclipse (you might need to install the buildship plugin)

**Comment by cer** [comment]
This [commit](https://github.com/microservices-patterns/ftgo-application/commit/f9e344417e69606b54d7396486e4bb146ea10834 ) should fix the grpc-related compilation errors.
