### ISSUE TITLE
Every time I do :composeUp and :composeDown will the data be persistent?

### ISSUE THREAD

**Issue by prakashid2** [microservices-patterns/ftgo-application#93]
One q. Every time I do :composeUp and :composeDown will the data be persistent? I had created consumer, restaurant and order earlier. That data I don't see anymore now. Does this(:composeUp) drop and recreate db?

The branch - wip-use-gradle-docker-compose

Thanks
Prakash S.

**Comment by dartartem** [comment]
Everything is removed.

> Stops containers and removes containers, networks, volumes, and images created by up

https://docs.docker.com/compose/reference/down/

**Comment by cer** [comment]
Containers can be configured to persist data on the host. However, you will need to read the docs to figure out how to do that.
